Improved protection for system + env variables
OrderOfTheBee/ootbee-support-tools pull request #202
Opened 2022-10-31 00:16 UTC by AFaust

### CHECKLIST

We will not consider a PR until the following items are checked off--thank you!

- [x] There aren't existing pull requests attempting to address the issue mentioned here
- [x] Submission developed in a feature branch--not master

### CONVINCING DESCRIPTION

This PR improves the protection of sensitive config properties in the System Information tools, specifically adding handling for Java arguments, system variables, and environment variables, specifically handling multiple `-D` props within env variables such as `JAVA_OPTS` / `JAVA_TOOL_OPTS` which will contain i.e. keystore in Alfresco's default images. This PR also extends the list of sensitive keys to include anything relating to credentials (i.e. LDAP credentials) and key data (if provided for Alfresco's automatic keystore creation).

### RELATED INFORMATION

Fixes #179

2022-11-02 08:33 UTC, RVanhuysseXenit requested changes

2022-11-02 08:33 UTC, RVanhuysseXenit commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.html.ftl
> +        <#local res = text?substring(0, nextEscapedWs + 2) + textUntilNextQuote(text?substring(nextEscapedWs + 2)) />
Should call `textUntilNextWs` instead?

2022-11-02 09:15 UTC, AFaust commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.html.ftl
> +        <#local res = text?substring(0, nextEscapedWs + 2) + textUntilNextQuote(text?substring(nextEscapedWs + 2)) />
Right - that was the intention, but apparently I forgot to adapt it fully after copy&pasting the quote-handling line. Thanks for noting that.

2022-11-05 17:24 UTC, AFaust commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.html.ftl
> +        <#local res = text?substring(0, nextEscapedWs + 2) + textUntilNextQuote(text?substring(nextEscapedWs + 2)) />
I fixed this template function call (and also added key protection in another tool it should be added).

2022-11-07 08:14 UTC, RVanhuysseXenit approved these changes

2022-11-07 08:39 UTC, merged