Saving/Updating Scripts in Subfolder
OrderOfTheBee/ootbee-support-tools pull request #211
Opened 2023-11-02 17:26 UTC by simonholzapfel

### CHECKLIST

We will not consider a PR until the following items are checked off--thank you!

- [x] There aren't existing pull requests attempting to address the issue mentioned here
- [x] Submission developed in a feature branch--not master

### CONVINCING DESCRIPTION

(JSConsole) Saving/Updating/Loading of Scripts in Subfolders

2024-02-19 12:32 UTC, p4535992 commented
Is this been integrated ? Or is still in progress ?

2024-02-19 20:32 UTC, AFaust requested changes
If you have a chance, please look through the review comments, and rebase against the latest state of the master branch (at that time).

2024-02-19 20:32 UTC, AFaust commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/jsconsole/saveScript.put.json.js
> +        return createFile(parent.childByNamePath(name) || parent.createFolder(name), path);
It would be good to validate that the return of `childByNamePath` is a folder/container node. E.g. currently when the user specifies `backup.js.sample/test.js` as a path, the save operation will fail but the error message will not be short and specific to the fact that the `backup.js.sample` is not a folder. Instead, an integrity violation is thrown and displayed, denoting that the `cm:contains` child association requires a `cm:folder` and is not supported for `cm:content`.

2024-02-19 20:32 UTC, AFaust commented on share/src/main/resources/META-INF/resources/components/ootbee-support-tools/jsconsole.js
> +                var scripts = JSON.parse(JSON.stringify(listOfScripts));
Please initialise the variable at the start of the function to align with the existing code style.

2024-02-19 20:32 UTC, AFaust commented on share/src/main/resources/META-INF/resources/components/ootbee-support-tools/jsconsole.js
> +                var scripts = JSON.parse(JSON.stringify(listOfScripts));
Please initialise the variable at the start of the function to align with the existing code style.

2024-02-19 20:32 UTC, AFaust commented on share/src/main/resources/META-INF/resources/components/ootbee-support-tools/jsconsole.js
> +                url: Alfresco.constants.PROXY_URI + 'ootbee/jsconsole/savescript.json?name=' + encodeURIComponent(nodeRef) + '&isUpdate=true',
Always using the `nodeRef` now would allow for the following general refactoring:

- removal of `isUpdate` argument
- using `nodeRef` argument instead of `name` argument in update use case
- adapt the `saveScript.put.json.js` to differentiate the udpate/create use cases based on presence of either ´name` (more like `namePath`) and `nodeRef`

Would you be willing to include this small refactoring when processing the review comments? It's not a must and I would have done it, but the PR/branch does not allow reviewers to add commits to it.

2024-02-19 20:32 UTC, AFaust commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/jsconsole/saveScript.put.json.js
> +                scriptFile = scriptFolder.childByNamePath(args.name);
See last comment on `jsconsole.js` - I think that case (update by name) is now obsolete and can be removed to always update by the NodeRef.

2024-02-19 20:32 UTC, AFaust commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/jsconsole/saveScript.put.json.js
> +var createFile = function createFile(parent, path) {
There does not need to be an assignment to a variable here.

2024-02-21 17:19 UTC, oboldyreva-faw commented on share/src/main/resources/META-INF/resources/components/ootbee-support-tools/jsconsole.js
> +                var scripts = JSON.parse(JSON.stringify(listOfScripts));
Done

2024-02-21 17:22 UTC, oboldyreva-faw commented on share/src/main/resources/META-INF/resources/components/ootbee-support-tools/jsconsole.js
> +                url: Alfresco.constants.PROXY_URI + 'ootbee/jsconsole/savescript.json?name=' + encodeURIComponent(nodeRef) + '&isUpdate=true',
Refactored both `jsconsole.js` and `saveScript.put.json.js` to use `nodeRef` and `namePath` arguments instead of `isUpdate`

2024-02-21 17:22 UTC, oboldyreva-faw commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/jsconsole/saveScript.put.json.js
> +                scriptFile = scriptFolder.childByNamePath(args.name);
Done

2024-02-21 17:22 UTC, oboldyreva-faw commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/jsconsole/saveScript.put.json.js
> +var createFile = function createFile(parent, path) {
Done

2024-02-21 17:24 UTC, oboldyreva-faw commented on repository/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/jsconsole/saveScript.put.json.js
> +        return createFile(parent.childByNamePath(name) || parent.createFolder(name), path);
added check and Error throw.

2024-02-21 17:46 UTC, AFaust approved these changes

2024-02-21 22:07 UTC, merged